CREATE TABLE r_medical_org_main
(
   reg_id integer NOT NULL, 
   ter_id integer NOT NULL, 
   lpu_id integer NOT NULL, 
   name character varying(200) NOT NULL, 
   addr character varying(254), 
   oms boolean NOT NULL, 
   CONSTRAINT pk_r_medical_org_main_reg_id_ter_id_lpu_id PRIMARY KEY (reg_id, ter_id, lpu_id), 
   CONSTRAINT fk_r_medical_org_main_reg_id_ter_id_r_medical_org_ter_reg_id_ter_id FOREIGN KEY (reg_id, ter_id) REFERENCES r_medical_org_ter (reg_id, ter_id) ON UPDATE NO ACTION ON DELETE NO ACTION
) 
WITH (
  OIDS = FALSE
)
;
COMMENT ON TABLE r_medical_org_main
  IS 'Медицинское учреждение';

INSERT INTO r_medical_org_main VALUES (42, 1, 5, 'МУУЗАГ Анжеро-Судженска', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 1, 6, 'МБУЗ Анжеро-Судженского городского округа "Центральная городская больница"', 'г.Анжеро-Судженск, ул.Кубанская, д. 3', true);
INSERT INTO r_medical_org_main VALUES (42, 1, 34, 'МУЗ "Детская городская поликлиника"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 1, 35, 'МУЗ "Городская поликлиника №5"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 1, 36, 'МУЗ "Городская поликлиника № 3"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 1, 37, 'МУЗ "Женская консультация"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 1, 40, 'МУЗ "Городская поликлиника №4"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 1, 41, 'МУЗ "Городская поликлиника №1"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 1, 42, 'МУЗ "Городская поликлиника №2"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 1, 44, 'МУЗ "Городская поликлиника 6"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 1, 47, 'МАУЗ Анжеро-Судженского городского округа "Стоматологическая поликлиника"', 'г.Анжеро-Судженск, ул. им. 50 летия Октября, 1', true);
INSERT INTO r_medical_org_main VALUES (42, 1, 48, 'А-Судженский психоневр. интернат департамента', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 1, 49, 'ГБУЗ КО "Анжеро-Судженский кожно-венерологический диспансер"', 'г.Анжеро-Судженск, ул.Топкинская, д.18', false);
INSERT INTO r_medical_org_main VALUES (42, 1, 50, 'МУ "Противотуберкулезный диспансер"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 1, 60, 'ССМП', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 1, 61, 'Гор.станция переливания крови', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 1, 65, 'Врач.физкульт.диспансер', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 1, 68, 'Санаторий "Анжерский"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 1, 69, 'МУЗ "Центр профессиональной патологии"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 1, 75, 'ФКУ СИЗО-4 ГУФСИН России по Кемеровской области', 'г.Анжеро-Судженск, ул.Чекистов, д.1', false);
INSERT INTO r_medical_org_main VALUES (42, 1, 901, 'Дом ребенка', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 1, 903, 'Противотуберкулезный детский санаторий', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 1, 904, 'Противотуберкулезный санаторий г.Анжеро-Судженска', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 1, 905, 'Дом сестринского ухода', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 1, 906, 'Ревмосанаторий', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 1, 980, 'ФКУ КП-31 ГУФСИН России по Кемеровской области', 'г.Анжеро-Судженск, ул. Чекистов, д.1', false);
INSERT INTO r_medical_org_main VALUES (42, 2, 3, 'МУ "Городская больница №7"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 2, 7, 'НУЗ "Узловая больница на станции Белово открытого акционерного общества "Российские железные дороги"', 'г.Белово, Микрорайон 3,д. 124', true);
INSERT INTO r_medical_org_main VALUES (42, 2, 9, 'МУЗ "Бел-кий межрайонный п/туберкулезный дис-р"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 2, 11, 'Врач.физкульт.диспансер', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 2, 12, 'МУЗ Беловский межрайонный психоневр.диспансер', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 2, 13, 'МБУЗ "Станция скорой медицинской помощи г.Белово"', 'г.Белово, ул.Чкалова, 16/2', false);
INSERT INTO r_medical_org_main VALUES (42, 2, 14, 'Станция переливания крови', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 2, 31, 'МБУ Городская больница № 1 г.Белово', 'г.Белово, ул.Чкалова, д.16', true);
INSERT INTO r_medical_org_main VALUES (42, 2, 32, 'МБУЗ "Детская городская больница № 1"', 'г.Белово, Микрорайон 3, 128', true);
INSERT INTO r_medical_org_main VALUES (42, 2, 33, 'МБУЗ "Городская инфекционная больница № 3"', 'г.Белово, ул.Энгельса, д.20', true);
INSERT INTO r_medical_org_main VALUES (42, 2, 34, 'МБУЗ "Городская больница № 4"', 'г.Белово, пгт.Инской, ул.Приморская, д.13', true);
INSERT INTO r_medical_org_main VALUES (42, 2, 35, 'МБУЗ "Городская больница № 8"', 'г.Белово, Микрорайон № 3, д.129', true);
INSERT INTO r_medical_org_main VALUES (42, 2, 37, 'МУЗ "Детская поликлиника 1"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 2, 50, 'МБУЗ "Городская больница № 2"', 'г.Белово, п.г.т. Новый городок, ул.Киевская, д.19', true);
INSERT INTO r_medical_org_main VALUES (42, 2, 51, 'ГБУЗ КО "Беловский кожно-венерологический диспансер"', 'г.Белово, ул.Люксембург, д.35а', false);
INSERT INTO r_medical_org_main VALUES (42, 2, 57, 'МУ "Городская поликлиника 2"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 2, 58, 'МБУ городская поликлиника № 3', 'г.Белово, п.г.т.Грамотеино, ул.Светлая, д.12', true);
INSERT INTO r_medical_org_main VALUES (42, 2, 73, 'МСЧ центра здоровья "Энергетик" Беловское', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 2, 75, 'МАУ Стоматологическая поликлиника г.Белово', 'г.Белово, ул.Советская, 69', true);
INSERT INTO r_medical_org_main VALUES (42, 2, 81, 'Линейная б-ца ст.Артышта', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 2, 143, 'МБУЗ Городская поликлиника № 6', 'г.Белово, п.г.т.Бачатский, ул.Шевцовой, д.23', true);
INSERT INTO r_medical_org_main VALUES (42, 2, 900, 'Упр. Здравоохранения Администрации г.Белово', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 2, 904, 'ГБУЗ Беловский детский противотуберкулезный санаторий', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 2, 941, 'МУЗ ЦСПИД г.Белово', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 2, 980, 'ФКУ ИК-44 ГУФСИН России по Кемеровской области', 'г.Белово, ул. Аэродромная, д.2Б/7', false);
INSERT INTO r_medical_org_main VALUES (42, 2, 990, 'ГУ ИДИ', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 2, 991, 'ГАУЗ КО "Центр здоровья "Инской"', 'г.Белово, п.г.т.Инской, ул.Ильича,6', false);
INSERT INTO r_medical_org_main VALUES (42, 3, 1, 'МБУЗ "Центральная городская больница"', 'г.Березовский, ул.Строителей, 2', true);
INSERT INTO r_medical_org_main VALUES (42, 3, 36, 'МУ "Городская поликлиника 1"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 3, 37, 'Барзасская амбулатория', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 3, 40, 'МБУЗ "Городская стоматологическая поликлиника"', 'г.Березовский, ул.Шахтёров, 1', true);
INSERT INTO r_medical_org_main VALUES (42, 3, 44, 'Врач.физкульт. диспансер', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 3, 46, 'ООО "Поликлиника № 4"', 'г.Березовский, ул.Черняховского, 4а', true);
INSERT INTO r_medical_org_main VALUES (42, 3, 53, 'ГУЗ "Обл.детский сан. для больных туберкулёзом"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 3, 54, 'ООО "Поликлиника "Боместра-Мед"', 'г.Березовский, пр-т Ленина, 54', false);
INSERT INTO r_medical_org_main VALUES (42, 3, 56, 'ООО "Травмпункт"', 'г.Березовский, ул.Ленина, д.13', true);
INSERT INTO r_medical_org_main VALUES (42, 3, 58, 'ООО "Центр здоровья СДС"', 'г.Березовский, АБК ЗАО "Черниговец"', true);
INSERT INTO r_medical_org_main VALUES (42, 3, 920, 'МБМУ "Станция скорой медицинской помощи"', 'г.Березовский, ул.Мира, д.13', false);
INSERT INTO r_medical_org_main VALUES (42, 3, 990, 'ГСУ Березовский ДДИ для умственно отсталых детей', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 4, 1, 'МУЗ "Городская больница"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 4, 36, 'МУ "Городская стоматологическая поликлиника"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 4, 40, 'Цех здоровья Металлургического завода', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 4, 41, 'ССМП', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 4, 990, 'ГУ ГПИ', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 1, 'МБУЗ "Городская клиническая больница № 1 имени М.Н.Горбуновой"', 'г.Кемерово, ул.Весенняя, 9а', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 2, 'МБУЗ "Городская клиническая больница № 2"', 'г.Кемерово, ул.Александрова, д. 7', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 3, 'МБУЗ "Кемеровский кардиологический диспансер"', 'г.Кемерово, ул.Сосновый бульвар, 6', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 6, 'МБУЗ "Детская городская клиническая больница № 5"', 'г.Кемерово, ул.Ворошилова, д.21', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 7, 'МБУЗ "Детская клиническая больница № 7"', 'г.Кемерово, ул.Гагарина, 134а', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 8, 'МБУЗ "Детская клиническая больница № 1"', 'г.Кемерово, пр.Ленина, 42а', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 10, 'МБУЗ "Детская клиническая больница № 2"', 'г.Кемерово, ул.Терешковой, д.7', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 11, 'ГАУЗ КО "Кемеровская областная клиническая больница"', 'г.Кемерово, пр.Октябрьский, 22', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 12, 'ГБУЗ КО "Кемеровская областная клиническая офтальмологическая больница"', 'г.Кемерово, пр.Октябрьский, 22 А', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 13, 'НУЗ "Отделенческая больница на станции Кемерово открытого акционерного общества "Российские железные дороги"', 'г.Кемерово, ул.Сибиряков-Гвардейцев, дом 9', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 14, 'ФГУЗ "МСЧ ГУВД Кемеровской области"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 15, 'ГБУЗ КО "Кемеровский областной клинический кожно-венерологический диспансер"', 'г.Кемерово, ул.Рукавишникова, д.41', false);
INSERT INTO r_medical_org_main VALUES (42, 5, 16, 'ГБУЗ КО "Областной клинический онкологический диспансер"', 'г.Кемерово, ул.Волгоградская, 35', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 17, 'ГБУЗ КО "Областной клинический госпиталь для ветеранов войн"', 'г.Кемерово, ул.50 лет Октября, д.10', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 18, 'МБУЗ "Больница №15"', 'г.Кемерово, ж.р.Кедровка, ул.Новогодняя, д.1', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 19, 'МБУЗ "Городская больница № 13"', 'г.Кемерово, ж.р. Ягуновский, ул.Масальская, д.68', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 20, 'Кемеровское ОАО "Азот"', 'г.Кемерово, ул.Грузовая, стр.1, КОАО "Азот"', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 21, 'ГБУЗ КО "Кемеровский областной клинический кожно-венерологический диспансер"', 'г.Кемерово, ул.Рукавишникова, д.41', false);
INSERT INTO r_medical_org_main VALUES (42, 5, 22, 'ГУЗ "Обл. клинический п/туберкулёзный диспансер"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 23, 'МБУЗ "Городская клиническая больница № 4"', 'г.Кемерово, ул.Невьянская, д.12', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 24, 'ФКУЗ "Медико-санитарная часть № 42 Федеральной службы исполнения наказаний"', 'г.Кемерово, ул.Красноармейская, д. 41', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 25, 'ФКУЗ "Медико-санитарная часть Министерства внутренних дел Российской Федерации по Кемеровской области"', 'г.Кемерово, ул.Кузбасская, д. 10а', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 26, 'МБУЗ "Детская поликлиника № 16"', 'г.Кемерово, пр-т.Ленинградский, д.12', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 37, 'МУЗ "Медико-санитарная часть № 17" "Строитель"', 'г.Кемерово, ул.Красноармейская, д.93', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 38, 'МАУЗ "Городская клиническая стоматологическая поликлиника № 1"', 'г.Кемерово, ул.50 лет Октября, 15', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 45, 'МАУЗ "Городская клиническая стоматологическая поликлиника № 2"', 'г.Кемерово, ул.Инициативная, д.16 б', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 55, 'МАУЗ "Городская клиническая стоматологическая поликлиника № 3"', 'г.Кемерово, пр.Шахтёров, д. 34', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 60, 'Поликлиника КВВКУС', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 61, 'МБУЗ "Городская клиническая поликлиника № 20"', 'г.Кемерово, ул.Сарыгина, д.42, пом. 65', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 63, 'ОАО "Кокс"', 'г.Кемерово, ул.1-ая Стахановская, 6', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 65, 'МБУЗ "Поликлиника № 6"', 'г.Кемерово, ул.Сергея Тюленина, д. 5Б', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 68, 'МУЗ "Клиническая стоматологическая поликлиника №4"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 81, 'МБУЗ "Клиническая поликлиника № 5"', 'г.Кемерово, пр. Ленина, д.107', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 86, 'МАУЗ "Городская клиническая стоматологическая поликлиника № 11"', 'г.Кемерово, пр.Ленинградский, д.41', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 98, 'Стомполиклиника 21', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 99, 'МУЗ "Городская стоматологическая поликлиника №19"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 124, 'Цех "Здоровье" АФ"ТОКЕМ"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 125, 'Научно-произ.пред."ЭКСЕРГИЯ"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 127, 'ГБУЗ "Дезинфекционная станция"', 'г.Кемерово, ул.Терешковой, д.52б, пом.73', false);
INSERT INTO r_medical_org_main VALUES (42, 5, 134, 'МБУЗ "Городская клиническая больница № 3 им. М.А.Подгорбунского"', 'г.Кемерово, ул.Островского, 22', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 136, 'МБУЗ "Городская клиническая больница № 11"', 'г.Кемерово, ул.Вахрушева, 4а', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 137, 'МБУЗ "Городская инфекционная клиническая больница № 8"', 'г.Кемерово, ул.Волгоградская, 43 б', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 138, 'Обл.наркодиспансер', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 141, 'МБУЗ "Городская клиническая станция скорой медицинской помощи"', 'г.Кемерово, ул.Волгоградская, д.39', false);
INSERT INTO r_medical_org_main VALUES (42, 5, 142, 'ООО ФИРМА "УЛЫБКА"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 143, 'Детский ортопед. санаторий', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 146, 'Дом ребенка', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 152, 'ГАУЗ КО "Областная клиническая стоматологическая поликлиника"', 'г.Кемерово, ул.50 лет Октября, 18', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 153, 'МБУЗ "Клинический консультативно-диагностический центр"', 'г.Кемерово, пр.Октябрьский, 53/1', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 154, 'Обл.патологоанатомич. бюро', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 158, 'ГЛПП Кемеровской области "Автомобилист"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 171, 'ЗАО Медико-санитарная часть "Центр здоровья "Энергетик"', 'г.Кемерово, ул. Кузбасская, д.37', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 172, 'Поликлиника МСЧ КЭМЗ', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 174, 'Консульт.поликлиника КГМИ', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 177, 'ФОЦ "Домостроитель"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 178, 'АО "Мелькорм"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 185, 'Гарнизонная поликлиника МО РФ', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 190, 'ФГБНУ "Научно-исследовательский институт комплексных проблем сердечно-сосудистых заболеваний"', 'г.Кемерово, ул.бульвар Сосновый , д. 6', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 201, 'Обл.врач.физкульт.диспансер', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 202, 'Кем.обл.центр народной медицины', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 203, 'Обл. станция переливания крови', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 204, 'Обл.бюро судмедэкспертизы', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 205, 'Обл.центр СПИД', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 206, 'Обл.психобольница', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 208, 'Областной хоспис', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 220, 'ММУ гор.центр мед.псих. помощи', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 223, 'Здрапункт разреза Кедровский', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 235, 'Центр медицины катастроф', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 237, 'Областной Ценр медицинской профилактики', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 238, 'МУЗ Центр медицинской профилактики', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 252, 'Индивид. предприн. Селицкий', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 260, 'МУЗ "Городской наркологический диспансер"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 300, 'ГБУЗ КО "Областной клинический перинатальный центр имени Л.А.Решетовой"', 'г.Кемерово, пр.Октябрьский, 22', false);
INSERT INTO r_medical_org_main VALUES (42, 5, 455, 'ООО "Лечебно-диагностический центр Международного института биологических систем Кемерово"', 'г.Кемерово, ул.Волгоградская, д.37', false);
INSERT INTO r_medical_org_main VALUES (42, 5, 457, 'ООО "Медэк"', 'г.Кемерово, пр.Октябрьский, 53/1-225', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 458, 'Санаторий Чайка', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 459, 'Санаторий Журавлик', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 460, 'ООО "ЭЛИГОМЕД И К"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 461, 'ООО "Медицинская практика"', 'г.Кемерово, пр.Шахтеров, д.47', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 462, 'ФГУ "98 поликлиника СибВО" Минобороны России', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 463, 'ООО "Кузбасская медицинская корпорация"', 'г.Кемерово, пр.Кузнецкий, д.103', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 470, 'МБУЗ "Центр общей врачебной практики"', 'г.Кемерово, пр.Шахтёров, д. 72', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 480, 'ООО "Сибирское здоровье"', 'г.Кемерово, ул.Волгоградская, д.43', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 485, 'ООО "Медицинский центр "Ваш доктор"', 'г.Кемерово, ул. Н.Островского, д.27', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 490, 'ООО "МЦ "Семейный доктор"', 'г.Кемерово, бр. Строителей, д.№ 28, корпус (строение) 1, литер А', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 495, 'ООО "Овум-Медико"', 'г.Кемерово, ул. Ноградская, д. 20, офис 1', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 499, 'ООО Кабинет лабораторных исследований "Овум"', 'г.Кемерово, ул. Ноградская, д.20-1', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 500, 'ООО Медицинский центр "Максимум здоровья"', 'г.Кемерово, пр.Химиков, д.8', true);
INSERT INTO r_medical_org_main VALUES (42, 5, 501, 'ООО "Лечебно-диагностический центр Международного института биологических систем Кемерово"', 'г.Кемерово, ул.Волгоградская, д.37', false);
INSERT INTO r_medical_org_main VALUES (42, 5, 502, 'ООО "Стоматологический центр"', 'г.Кемерово, ул.Стадионная, д.4Б', false);
INSERT INTO r_medical_org_main VALUES (42, 5, 503, 'ООО "МИКС"', 'г.Кемерово, пр.Советский, д.6,офис 3', false);
INSERT INTO r_medical_org_main VALUES (42, 5, 504, 'ЗАО "Современные медицинские технологии"', 'г.Кемерово, ул.Рукавишникова, д.22', false);
INSERT INTO r_medical_org_main VALUES (42, 5, 505, 'ООО "Центр озонотерапии "МЕДОЗОНЪ"', 'г.Кемерово, ул.Кузбасская, д.37', false);
INSERT INTO r_medical_org_main VALUES (42, 5, 506, 'ООО МЦ "МЕДПРОФ"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 507, 'ООО "Блеск"', 'г.Кемерово, пр.Ленина, д.14', false);
INSERT INTO r_medical_org_main VALUES (42, 5, 508, 'ООО "Блеск-2"', 'г.Кемерово, пр.Кузнецкий, д.119А', false);
INSERT INTO r_medical_org_main VALUES (42, 5, 509, 'ООО "КУЗБАССКИЙ ОФТАЛЬМОЛОГИЧЕСКИЙ ЦЕНТР"', 'г.Кемерово, ул.Рукавишникова, д.20', false);
INSERT INTO r_medical_org_main VALUES (42, 5, 510, 'ООО "АМИТА"', 'г.Кемерово, ул.1-я Линия, д.14', false);
INSERT INTO r_medical_org_main VALUES (42, 5, 511, 'ООО "Интермедиа"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 512, 'ООО "Медицинский Центр "Надежда"', 'г.Кемерово, ул. Николая Островского, д.22', false);
INSERT INTO r_medical_org_main VALUES (42, 5, 513, 'АНО "Диагностический центр женского здоровья "Белая роза""', 'г.Кемерово, пр.Октябрьский, д.22 в, оф.2005', false);
INSERT INTO r_medical_org_main VALUES (42, 5, 905, 'Дом ребенка 1', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 909, 'Управление транспортом ДОЗН', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 980, 'ФКУ ИК-5 ГУФСИН России по Кемеровской области', 'г.Кемерово, ул. Буденного, д.48', false);
INSERT INTO r_medical_org_main VALUES (42, 5, 981, 'ФКУ ИК-29 ГУФСИН России по Кемеровской области', 'г.Кемерово, ул. Стройгородок', false);
INSERT INTO r_medical_org_main VALUES (42, 5, 982, 'ФКУ ИК-40 ГУФСИН России по Кемеровской области', 'г.Кемерово, ул. Волгоградская, д.60А', false);
INSERT INTO r_medical_org_main VALUES (42, 5, 983, 'ФКУ ИК-43 ГУФСИН России по Кемеровской области', 'г.Кемерово, ул. Баха, д.3А', false);
INSERT INTO r_medical_org_main VALUES (42, 5, 984, 'ФКУ СИЗО-1 ГУФСИН России по Кемеровской области', 'г.Кемерово, пр.Кузнецкий, д.174', false);
INSERT INTO r_medical_org_main VALUES (42, 5, 990, 'ГУ КПНИ ДСЗНКО', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 991, 'ГУ СО Кемеровский дом-интернат для престарелых', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 992, 'Санаторий "Искорка"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 5, 993, 'ООО "АВРОРА"', 'г.Кемерово, пр-т Октябрьский, д.49', false);
INSERT INTO r_medical_org_main VALUES (42, 5, 994, 'ООО "МЦ "Мегаполис"', 'г.Кемерово, ул.Марковцева, д.10, пом. 133', false);
INSERT INTO r_medical_org_main VALUES (42, 5, 995, 'МБУЗ "Городская клиническая больница № 11"', 'г.Кемерово, ул.Вахрушева, д.4а', false);
INSERT INTO r_medical_org_main VALUES (42, 6, 1, 'МБУ "Городская больница № 2"', 'г.Киселевск, ул.Ленина, д.27', true);
INSERT INTO r_medical_org_main VALUES (42, 6, 2, 'МБУ "Городская больница № 1"', 'г.Киселевск, ул.Ленина, д. 31', true);
INSERT INTO r_medical_org_main VALUES (42, 6, 3, 'МБУ "Детская городская больница"', 'г.Киселевск, ул.Ленина, д. 27А', true);
INSERT INTO r_medical_org_main VALUES (42, 6, 21, 'МАУ "Городская стоматологическая поликлиника"', 'г.Киселевск, ул.Советская, 8', true);
INSERT INTO r_medical_org_main VALUES (42, 6, 22, 'Стомполиклиника', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 6, 34, 'ГБУЗ КО "Киселевский кожно-венерологический диспансер"', 'г.Киселевск, ул. 1-ое Мая, 1а', false);
INSERT INTO r_medical_org_main VALUES (42, 6, 35, 'Мед центр "ЗДОРОВЬЯ"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 6, 36, 'АПО МСЧ АОЗТ ш.Вахрушева', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 6, 43, 'Патологоанатомическое бюро', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 6, 46, 'Врачебно-физкульт. диспансер', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 6, 47, 'Психоневрологический диспансер', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 6, 48, 'МБУ "Станция скорой медицинской помощи"', 'г.Киселевск, ул.Ленина, д.20', false);
INSERT INTO r_medical_org_main VALUES (42, 6, 49, 'Станция переливания крови', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 6, 90, 'Центр. мед профилактики', 'г.Киселевск, ул.Советская, д.3а', false);
INSERT INTO r_medical_org_main VALUES (42, 6, 91, 'МУ "Противотуберкулёзный диспансер"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 6, 94, 'ООО "Поликлиника"', 'г.Киселевск, ул.Дзержинского, д.6', true);
INSERT INTO r_medical_org_main VALUES (42, 6, 95, 'ООО "ЛеОМеД"', 'г.Киселевск, ул.Советская, д.3а', true);
INSERT INTO r_medical_org_main VALUES (42, 6, 96, 'ГУЗ Дом ребенка', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 6, 909, 'Упр. Здравоохранения Администрации Киселевска', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 6, 930, 'Центр профилактики и борьбе со СПИД и И', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 6, 931, 'ООО поликлиника "Медицинский центр"', 'г.Новосибирск г.Киселевск, ул.Дзержинского,1', false);
INSERT INTO r_medical_org_main VALUES (42, 6, 932, 'ООО "Амбулаторно-поликлинический центр "Регион-Мед"', 'г.Киселевск, ул.Седова, д.2', false);
INSERT INTO r_medical_org_main VALUES (42, 7, 2, 'МБУЗ "Городская больница № 1"', 'г.Ленинск-Кузнецкий, ул.Мусохранова, д. 5', true);
INSERT INTO r_medical_org_main VALUES (42, 7, 4, 'ФГБЛПУ "Научно-клинический центр охраны здоровья шахтеров"', 'г.Ленинск-Кузнецкий, 7-й Микрорайон, д. 9', true);
INSERT INTO r_medical_org_main VALUES (42, 7, 6, 'МАУЗ "Городская поликлиника № 3"', 'г.Ленинск-Кузнецкий, ул.Чекмарева, д.28А', true);
INSERT INTO r_medical_org_main VALUES (42, 7, 7, 'МУЗ "Противотуберкулезный диспансер"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 7, 8, 'ГБУЗ КО "Ленинск-Кузнецкий кожно-венерологический диспансер"', 'г.Ленинск-Кузнецкий, ул.Орджоникидзе, д.25', false);
INSERT INTO r_medical_org_main VALUES (42, 7, 9, 'Псих.больница', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 7, 11, 'МБУЗ "Станция скорой медицинской помощи"', 'г.Ленинск-Кузнецкий, ул.Горького, д.36', false);
INSERT INTO r_medical_org_main VALUES (42, 7, 12, 'Станция переливания крови', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 7, 50, 'МБУЗ "Городская инфекционная больница"', 'г.Ленинск-Кузнецкий, ул.Чекмарёва, д.7', true);
INSERT INTO r_medical_org_main VALUES (42, 7, 65, 'Врачебно-физкульт. диспансер', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 7, 66, 'Патологоанатомическое бюро', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 7, 68, 'МБУЗ "Стоматологическая поликлиника № 1"', 'г.Ленинск-Кузнецкий, ул.Пушкина, 3', true);
INSERT INTO r_medical_org_main VALUES (42, 7, 69, 'МУЗ "Стоматологическая поликлиника №2"', 'г.Ленинск-Кузнецкий, пр.Кольчугинский, д.3', false);
INSERT INTO r_medical_org_main VALUES (42, 7, 300, 'Упр. Здравоохранения Администрации г. Л-Кузнецкий', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 7, 901, 'ММУ Детский Гастроэнтерологический санаторий', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 7, 902, 'Дом сестринского ухода', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 7, 903, 'Автохозяйство', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 7, 904, 'МУЗ ЦПСПИД', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 7, 906, 'Детский ревматологический санаторий', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 7, 907, 'ГБУЗ Ленинск-Кузнецкий детский противотуберкулезный санаторий', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 7, 980, 'ФКУ ЛИУ-42 ГУФСИН России по Кемеровской области', 'Ленинск-Кузнецкий, Северная промзона, №15', false);
INSERT INTO r_medical_org_main VALUES (42, 7, 981, 'ФКУ Ленинск-Кузнецкая ВК ГУФСИН России по Кемеровской области', 'г.Ленинск-Кузнецкий, Северная промзона №11', false);
INSERT INTO r_medical_org_main VALUES (42, 8, 1, 'МБУЗ "Центральная городская больница"', 'г.Междуреченск, пр.50 лет Комсомола, д.39', true);
INSERT INTO r_medical_org_main VALUES (42, 8, 2, 'ГУЗ "Узл. б-ца на ст.Новокузнецк" Междуреч. отдел.', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 8, 3, 'МЛПУ "Городской п/туберкулёзный диспансер"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 8, 37, 'Узл. б-ца на ст.Новокузнецк Междуреч. отдел.', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 8, 38, 'Поликлиника профосмотров', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 8, 42, 'Стомполиклиника', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 8, 44, 'Врач.физкульт.диспансер', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 8, 45, 'Психоневр.диспансер', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 8, 46, 'ССМП', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 8, 47, 'Станция переливания крови', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 8, 50, 'МАУ "Оздоровительный центр "Солнечный"', 'г.Междуреченск, район шахты имени Ленина', false);
INSERT INTO r_medical_org_main VALUES (42, 8, 980, 'ФКУ КП-14 ГУФСИН России по Кемеровской области', 'г.Междуреченск, п.Майзас, ул. Майзаская', false);
INSERT INTO r_medical_org_main VALUES (42, 8, 981, 'ФКУ ОУХД КП-11 ГУФСИН России по Кемеровской области', 'г.Междуреченск, пос. Ортон', false);
INSERT INTO r_medical_org_main VALUES (42, 9, 1, 'МБУЗ "Центральная городская больница"', 'Мысковский городской округ, б-р.Юбилейный, д. 2', true);
INSERT INTO r_medical_org_main VALUES (42, 9, 38, 'МУ "Муниципальная стоматологическая поликлиника"', 'г.Мыски, ул.Кузнецкая, 3', true);
INSERT INTO r_medical_org_main VALUES (42, 9, 40, 'Наркологический кабинет', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 9, 41, 'Тубдиспансер', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 9, 42, 'Томь-Усинское подразделение МСЧ ц. зд."Энергетик"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 9, 43, 'Станция перелив.крови', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 9, 990, 'МДИ', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 10, 'Центр "СПИД"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 11, 'Новокузнецкая медицина', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 12, 'МЛПУ Конс.-диагн.пол-ка "Центр диаг. и кор. нейровегет., психосом. и проф. нарушений"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 13, 'Центр профпатологии', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 14, 'МБЛПУ "Амбулатория № 4 (общая врачебная практика)"', 'г.Новокузнецк, ул.Шолохова, 5', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 15, 'МБЛПУ "Городская поликлиника № 1 (общая врачебная практика)"', 'г.Новокузнецк, пр.Кузнецкстроевский, 17', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 16, 'МЛПУ Общая врачебная практика 3', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 17, 'ЭЛИГОМЕД (Медицинский центр)', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 19, 'НУЗ "Узловая больница на станции Новокузнецк открытого акционерного общества "Российские железные дороги"', 'г.Новокузнецк, ул.Стальского, д.1', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 20, 'МБЛПУ "Городская клиническая больница № 1"', 'г.Новокузнецк, Центральный район, просп. Бардина, д.28', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 21, 'МБЛПУ "Городская клиническая больница № 2 Святого великомученика Георгия Победоносца"', 'г.Новокузнецк, ул.Кузнецова, 35', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 22, 'МБЛПУ "Детская городская клиническая больница № 3"', 'г.Новокузнецк, ул. 13-й микрорайон, 7', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 23, 'МБЛПУ "Городская детская клиническая больница № 4"', 'г.Новокузнецк, ул.Димитрова, д.33', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 24, 'МБЛПУ "Городская клиническая больница № 5"', 'г.Новокузнецк, ул.Димитрова, 31', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 25, 'МБЛПУ "Городская детская больница №6"', 'г.Новокузнецк, ул.Петракова, 65', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 26, 'Детская гор.боль-ца ДГБ7 (Таргай)', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 27, 'МБЛПУ "Городская клиническая инфекционная больница № 8"', 'г.Новокузнецк, ул.Медицинская, 36', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 28, 'МБЛПУ "Городская клиническая поликлиника № 9"', 'г.Новокузнецк ул.Хитарова, д.32', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 30, 'МБЛПУ "Городская клиническая больница № 11"', 'г.Новокузнецк, ул.Дузенко, д.7', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 31, 'Психиатрическая больница 12', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 32, 'Центр охраны здоровья "МиР"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 35, 'МБЛПУ "Городская больница № 16"', 'г.Новокузнецк, проезд Дагестанский, д.4', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 36, 'ФГБУ "Научно-исследовательский институт комплексных проблем гигиены и проф. заболеваний" СО РАМН', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 38, 'МЛПУ "Городская клин.туб. б-ца 19"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 39, 'Общая врачебная практика п.Тагарыш', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 41, 'МБЛПУ "Городская клиническая больница № 22"', 'г.Новокузнецк, ул.Петракова, 71', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 43, 'ООО "Медицинский центр "Спас 03"', 'г.Новокузнецк, пр.Советской Армии, д.59', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 45, 'МБЛПУ "Городская больница № 26"', 'г.Новокузнецк, ул.Ливинская, 3а', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 47, 'МБЛПУ "Городская детская больница №28"', 'г.Новокузнецк, ул. День Шахтера, 2', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 48, 'МБЛПУ "Городская клиническая больница № 29"', 'г.Новокузнецк, проспект Советской Армии, 49', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 50, 'ГБУЗ "Новокузнецкий клинический онкологический диспансер"', 'г.Новокузнецк, ул.Кутузова, 25', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 51, 'МБЛПУ "Станция скорой медицинской помощи"', 'г.Новокузнецк, пр.Бардина, д.28', false);
INSERT INTO r_medical_org_main VALUES (42, 10, 52, 'ГБУЗ КО "Новокузнецкий клинический кожно-венерологический диспансер"', 'г.Новокузнецк, пр.Октябрьский, д.2', false);
INSERT INTO r_medical_org_main VALUES (42, 10, 53, 'ФКЛПУ "Больница №2 Главного управления Федеральной службы исполнения наказаний по Кемеровской области"', 'г.Новокузнецк, ул.Кутузова, 62', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 57, 'Врач.физкульт.диспансер', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 58, 'Наркологический диспансер', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 60, 'МЛПУ "Городская поликлиника КМК"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 62, 'МБЛПУ "Клинический родильный дом № 3"', 'г.Новокузнецк, ул.Авиаторов, 88', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 63, 'Родильный дом РД1', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 64, 'МБЛПУ "Родильный дом № 2"', 'г.Новокузнецк, пр.Ижевский, д. 16', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 66, 'ФГБУ "Новокузнецкий научно-практический центр медико-социальной экспертизы и реабилитации инвалидов" Министерства труда и социальной защиты Российской Федерации', 'г.Новокузнецк, ул.Малая, д.7', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 70, 'Стомп-ка АО "Кузн.ферросплав"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 71, 'МБЛПУ "Городская клиническая стоматологическая поликлиника № 1"', 'г.Новокузнецк, ул.Кирова, д.91, 93', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 72, 'МБЛПУ "Городская стоматологическая поликлиника № 2"', 'г.Новокузнецк, ул.Метелкина, 16', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 73, 'МБЛПУ "Городская стоматологическая поликлиника № 3"', 'г.Новокузнецк, ул.Клименко, 29', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 74, 'МБЛПУ "Городская стоматологическая поликлиника № 4"', 'г.Новокузнецк, ул.Пржевальского, д. 24', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 75, 'МБЛПУ "Детская стоматологическая поликлиника № 5"', 'г.Новокузнецк, пр.Кузнецкстроевский, д.20', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 76, 'МБЛПУ "Городская стоматологическая поликлиника № 6"', 'г.Новокузнецк, ул.Карла Маркса, 12', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 78, 'Стомп-ка АООТ "НКАЗ"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 83, 'МБЛПУ "Зональный перинатальный центр"', 'г.Новокузнецк, ул.Сеченова, 26', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 91, 'ГУ "Дезинфекционная станция в г.Новокузнецке КО"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 92, 'Санаторий 1 гепатитный,кишечный', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 93, 'Санаторное отд.больницы 3 для детей', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 94, 'Санаторий 3 многопрофильный', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 95, 'Санаторий "Таргайский" пульманол.,аллерг', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 96, 'ГБУЗ Новокузнецкий детский психоневрологический санаторий 3', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 97, 'Детский санаторий 5', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 98, 'ГБУЗ Новокузнецкий детский психоневрологический санаторий 2', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 99, 'Санаторий 7 "Колосок"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 100, 'ООО "Медицинский центр "Ваш доктор"', 'г.Новокузнецк, ул. Сеченова, д.28А-408', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 102, 'ООО "ЧВП "Домашний врач"', 'г.Новокузнецк, ул.Кирова, д.103', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 104, 'ООО Санаторий профилакторий Нарцисс', 'г.Новокузнецк, ул.Кутузова, д.36', true);
INSERT INTO r_medical_org_main VALUES (42, 10, 105, 'ГБУЗ Новокузнецкий детский психоневрологический санаторий 1', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 118, 'МСЧ КМК', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 150, 'ООО "Медика"', 'г.Новокузнецк, ул.Сеченова, д.30', false);
INSERT INTO r_medical_org_main VALUES (42, 10, 152, 'ООО "Стоматологическая поликлиника "Запсиб Дент"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 665, 'Кемеровская региональная общественная организация "Центр реабилитации инвалидов и ветеранов"', 'г.Новокузнецк, ул. Невского, д.11', false);
INSERT INTO r_medical_org_main VALUES (42, 10, 670, 'ООО "Лечебно-диагностический центр Международного института биологических систем - Новокузнецк"', 'г. Новокузнецк, ул. Димитрова, д.33', false);
INSERT INTO r_medical_org_main VALUES (42, 10, 675, 'ООО "Максидент"', 'г.Новокузнецк, пр.Сеченова, д.28, корпус a,офис 412', false);
INSERT INTO r_medical_org_main VALUES (42, 10, 676, 'ЧУ "Медико-образовательная организация "Нефрологический экспертный совет"', 'г.Кемерово, пр.Октябрьский,д.4', false);
INSERT INTO r_medical_org_main VALUES (42, 10, 800, 'Общая врачебная практика п.Тагарыш', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 810, 'ООО "Санаторий-профилакторий "Полосухинский"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 811, 'ООО "Медицинский клуб"', 'г.Новокузнецк, пр.Бардина, д.30, корпус 2', false);
INSERT INTO r_medical_org_main VALUES (42, 10, 812, 'ООО "Центр общей врачебной (семейной) практики "Фамилия"', 'г.Новокузнецк, ул.Тольятти, д.48, пом 39', false);
INSERT INTO r_medical_org_main VALUES (42, 10, 901, 'Психоневрологический дом ребенка 1', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 902, 'Психоневрологический дом ребенка 2', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 903, 'Городское патологоанатомическое бюро', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 904, 'Детский психоневрологический санаторий 8', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 905, 'Обьединение молочных кухонь', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 906, 'Бюро судебно-медицинской экспертизы', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 980, 'ФКУ ИК-12 ГУФСИН России по Кемеровской области', 'г.Новокузнецк, пос. Абагур-Лесной ул. Орловой, д.20', false);
INSERT INTO r_medical_org_main VALUES (42, 10, 981, 'ФКУ ЛИУ-16 ГУФСИН России по Кемеровской области', 'г.Новокузнецк, ул. Левашова, д.42А', false);
INSERT INTO r_medical_org_main VALUES (42, 10, 982, 'ФКУ СИЗО-2 ГУФСИН России по Кемеровской области', 'г.Новокузнецк, ул.Полосухина, д.3', false);
INSERT INTO r_medical_org_main VALUES (42, 10, 990, 'ГСУ Новокузнецкий дом-интернат для престарелых', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 991, 'НДИ 2', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 10, 993, 'ООО "Независимая лаборатория"', 'г.Новокузнецк, ул.Энтузиастов, д. 32', false);
INSERT INTO r_medical_org_main VALUES (42, 10, 994, 'ООО "Валеомед"', 'г.Новокузнецк, ул.Хитарова, д. 30', false);
INSERT INTO r_medical_org_main VALUES (42, 10, 995, 'ООО "Медиа-Сервис"', 'г.Новокузнецк, ул.Фестивальная, д. 5', false);
INSERT INTO r_medical_org_main VALUES (42, 11, 1, 'МБУЗ "Городская больница" Осинниковского городского округа', 'г.Осинники, ул.Больничный Городок, д. 44/2', true);
INSERT INTO r_medical_org_main VALUES (42, 11, 20, 'Станция переливания крови', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 11, 21, 'МБУЗ Станция скорой медицинской помощи Осинниковского городского округа', 'г.Осинники, ул. Магистральный Проезд, д.20', false);
INSERT INTO r_medical_org_main VALUES (42, 11, 24, 'МАУЗ Стоматологическая поликлиника', 'г.Осинники, ул.Победы, 46', true);
INSERT INTO r_medical_org_main VALUES (42, 11, 32, 'МУЗ "Городская поликлиника г. Осинники"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 11, 34, 'МБУЗ Детская городская больница', 'г.Осинники, ул.Больничный Городок, д. 60', true);
INSERT INTO r_medical_org_main VALUES (42, 11, 35, 'МУЗ Родильный дом г. Осинники', 'г.Осинники, ул.50 лет Октября, д. 7', false);
INSERT INTO r_medical_org_main VALUES (42, 11, 36, 'Инфекционная больница', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 11, 37, 'ГБУЗ КО "Осинниковский кожно-венерологический диспансер"', 'г.Осинники, ул.Крупской, 56', false);
INSERT INTO r_medical_org_main VALUES (42, 11, 43, 'МУЗ "Городская больница п. Малиновка"', 'г.Осинники, пос.Малиновка, ул.60 лет Октября, 1', false);
INSERT INTO r_medical_org_main VALUES (42, 11, 46, 'МУЗ г. Осинники "Городская поликлиника № 2"', 'г.Осинники, ул.Коммунистическая, 29', false);
INSERT INTO r_medical_org_main VALUES (42, 11, 55, 'ЗАО "Фамилия"', 'г.Осинники, ул. Ленина, д.129, помещение 14', false);
INSERT INTO r_medical_org_main VALUES (42, 11, 101, 'ООО "ЛеОМеД"', 'г.Киселевск, ул.Советская, д.3а', true);
INSERT INTO r_medical_org_main VALUES (42, 11, 900, 'Управление здравоохранения г.Осинники', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 11, 930, 'МУЗ Сарбаллинская врачебная амбулатория', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 11, 990, 'ГУ МПН', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 12, 1, 'МБУЗ "Городская больница № 4"', 'г.Прокопьевск, ул.Прокопьевская, д.54', true);
INSERT INTO r_medical_org_main VALUES (42, 12, 2, 'МБУЗ "Городская больница № 3"', 'г.Прокопьевск, ул.Городская, д.116', true);
INSERT INTO r_medical_org_main VALUES (42, 12, 4, 'МБУЗ "Городская больница № 1"', 'г.Прокопьевск, ул.Подольская, 12', true);
INSERT INTO r_medical_org_main VALUES (42, 12, 5, 'МБУЗ "Детская городская больница"', 'г.Прокопьевск, пр.Строителей, д.7', true);
INSERT INTO r_medical_org_main VALUES (42, 12, 6, 'МБУЗ "Городская инфекционная больница"', 'г.Прокопьевск, ул.Подольская, д.14', true);
INSERT INTO r_medical_org_main VALUES (42, 12, 7, 'МУЗ "Туберкулезная больница"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 12, 8, 'ГБУЗ КО "Областная клиническая ортопедо-хирургическая больница восстановительного лечения"', 'г.Прокопьевск, ул.Вокзальная, 65', true);
INSERT INTO r_medical_org_main VALUES (42, 12, 9, 'ГБУЗ КО "Прокопьевский кожно-венерологический диспансер"', 'г.Прокопьевск, ул. Ноградская, д.4', false);
INSERT INTO r_medical_org_main VALUES (42, 12, 10, 'МБУЗ "Городская поликлиника"', 'г.Прокопьевск, пр.Строителей, д. 7', true);
INSERT INTO r_medical_org_main VALUES (42, 12, 11, 'ГУЗ "Узл. б-ца на ст.Белово"Стац. и пол. отд. на ст. Прокопьевск', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 12, 12, 'МБУЗ "Городская больница № 2"', 'г.Прокопьевск, ул.Карьерная, 46', true);
INSERT INTO r_medical_org_main VALUES (42, 12, 59, 'МАУЗ "Городская стоматологическая поликлиника № 1"', 'г.Прокопьевск, ул.Яворского, д.24', true);
INSERT INTO r_medical_org_main VALUES (42, 12, 60, 'МАУЗ "Городская стоматологическая поликлиника № 2"', 'г.Прокопьевск, ул.космонавта Волынова, д13', true);
INSERT INTO r_medical_org_main VALUES (42, 12, 62, 'НУЗ "УЗЛОВАЯ БОЛЬНИЦА НА СТАНЦИИ БЕЛОВО ОАО "РЖД" ОТДЕЛЕНИЕ НА СТАНЦИИ ПРОКОПЬЕВСК', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 12, 77, 'Цетр планиров семьи и репродук', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 12, 79, 'Центр для инвалидов', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 12, 91, 'Врачебно-физкультурный диспан.', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 12, 92, 'МБУЗ "Городская станция скорой медицинской помощи"', 'г.Прокопьевск, ул. Институтская, д.30', false);
INSERT INTO r_medical_org_main VALUES (42, 12, 93, 'Станция перелив.крови', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 12, 97, 'Психбольница', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 12, 99, 'Наркодиспансер', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 12, 101, 'Патологанатомическое бюро', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 12, 200, 'ООО "Клиника медицинских осмотров"', 'г.Прокопьевск, ул. Яворского, д.22', true);
INSERT INTO r_medical_org_main VALUES (42, 12, 201, 'ООО "Лео-М"', 'г.Прокопьевск, ул. Яворского, д.22', true);
INSERT INTO r_medical_org_main VALUES (42, 12, 202, 'ООО "ЛеОКон"', 'г.Прокопьевск, ул. Яворского, д.22', true);
INSERT INTO r_medical_org_main VALUES (42, 12, 205, 'ОАО "Санаторий "Прокопьевский"', 'г.Прокопьевск, ул.Парковая, д.280', true);
INSERT INTO r_medical_org_main VALUES (42, 12, 207, 'ГБУЗ Прокопьевский детский психоневрологический санаторий', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 12, 208, 'ООО "Санаторий "Шахтер"', 'г.Прокопьевск, Зенковский парк', false);
INSERT INTO r_medical_org_main VALUES (42, 12, 209, 'ООО "Медицинский центр "Орбита здоровья"', 'г.Прокопьевск, ул.Гайдара, д.50А, оф.701', false);
INSERT INTO r_medical_org_main VALUES (42, 12, 215, 'ООО "Центр лучевой диагностики"', 'г.Прокопьевск, ул. Яворского, д.22', false);
INSERT INTO r_medical_org_main VALUES (42, 12, 216, 'ООО "Медицинская практика"', 'г.Прокопьевск, ул. Яворского, д.22', false);
INSERT INTO r_medical_org_main VALUES (42, 12, 217, 'OOO "Лабораторная диагностика"', 'г.Прокопьевск, ул. Яворского, д.22', false);
INSERT INTO r_medical_org_main VALUES (42, 12, 218, 'ООО " БЛЕСК "', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 12, 219, 'ООО "Центр реабилитации и восстановления"', 'г.Прокопьевск, ул. Яворского, д.22', false);
INSERT INTO r_medical_org_main VALUES (42, 12, 901, 'ММУ Детский санаторий 1', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 12, 902, 'ММУ Дом ребенка', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 12, 903, 'Молочная кухня', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 13, 1, 'НУЗ "Узловая больница на станции Тайга открытого акционерного общества "Российские железные дороги"', 'г.Тайга, ул.Щетинкина, 61', true);
INSERT INTO r_medical_org_main VALUES (42, 13, 20, 'МБМУ "Станция скорой медицинской помощи г.Тайги"', 'г.Тайга, ул.Щетинкина, 61', false);
INSERT INTO r_medical_org_main VALUES (42, 13, 980, 'ФКУ ЛИУ-21 ГУФСИН России по Кемеровской области', 'г.Тайга, п.Таежный, ул.Народная, 7', false);
INSERT INTO r_medical_org_main VALUES (42, 13, 990, 'ГУ ТПИ', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 14, 1, 'МБУЗ "Таштагольская Центральная районная больница"', 'г.Таштагол, ул. Ленина, 7', true);
INSERT INTO r_medical_org_main VALUES (42, 14, 2, 'МУЗ "Районная больница №2"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 14, 15, 'МУ городской п/туберкулезный диспансер', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 14, 25, 'МАУ "Городская стоматологическая поликлиника"', 'г.Таштагол, ул.Поспелова, д. 27', true);
INSERT INTO r_medical_org_main VALUES (42, 14, 26, 'Кожвендиспансер', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 14, 933, 'Узловая б-ца Амбулаторно-пол-кое отд-е', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 14, 980, 'ФКУ ОУХД ИК-4 ГУФСИН России по Кемеровской области', 'Таштагольский район, п.Шерегеш, ул.Весенняя, д.9', false);
INSERT INTO r_medical_org_main VALUES (42, 15, 1, 'МУЗ "Центральная городская больница г.Юрги"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 15, 2, 'МБУЗ "Городская больница № 1 города Юрги"', 'г.Юрга, ул.Ленинградская, д.27', true);
INSERT INTO r_medical_org_main VALUES (42, 15, 3, 'ФГУ "1148 ВГ СибВО" Минобороны России', 'г.Юрга, ФГУ "1148 ВГ СибВО" Минобороны России', true);
INSERT INTO r_medical_org_main VALUES (42, 15, 4, 'МБУЗ "Городская больница №2 города Юрги"', 'г.Юрга, ул.Машиностроителей, д.5', true);
INSERT INTO r_medical_org_main VALUES (42, 15, 29, 'Поликлиника профосмотров', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 15, 44, 'МБУЗ "Стоматологическая поликлиника"', 'г.Юрга, ул.Волгоградская, д.7', true);
INSERT INTO r_medical_org_main VALUES (42, 15, 45, 'МБУЗ "Станция скорой медицинской помощи города Юрги"', 'г.Юрга, ул. Достоевского, д.3', false);
INSERT INTO r_medical_org_main VALUES (42, 15, 46, 'Врач.физкульт.диспансер', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 15, 47, 'Психоневролог.диспансер', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 15, 51, 'Противотуберкулёзный диспансер', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 15, 53, 'Городское отд.КЕМ.ОБЛ.пат.бюро', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 15, 54, 'Детский противотуб. диспансер', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 15, 55, 'ООО "Поликлиника "Общая (групповая) врачебная практика"', 'г.Юрга, ул.Заводская, 14', true);
INSERT INTO r_medical_org_main VALUES (42, 15, 80, 'ООО "Врачебная практика "Здоровье и красота"', 'г.Юрга, пр. Победы, д.15', true);
INSERT INTO r_medical_org_main VALUES (42, 15, 85, 'ООО "Медицинский центр "Здоровье"', 'г.Юрга, улица Ленинградская, д.9', true);
INSERT INTO r_medical_org_main VALUES (42, 15, 86, 'ГБУЗ КО "Юргинский кожно-венерологический диспансер"', 'г.Юрга, ул. Машиностроителей, д.2б', false);
INSERT INTO r_medical_org_main VALUES (42, 15, 90, 'Поликлиника профилактической медицины ООО "Био-Мед"', 'г.Юрга, ул. Заводская, д.14', false);
INSERT INTO r_medical_org_main VALUES (42, 15, 91, 'ООО "Блеск"', 'г.Юрга, ул. Строительная, д.17, пом.71', false);
INSERT INTO r_medical_org_main VALUES (42, 15, 904, 'ГБУЗ Юргинский детский противотуберкулезный санаторий', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 15, 980, 'ФКУ ИК-41 ГУФСИН России по Кемеровской области', 'г.Юрга, ул.Окрайная,1', false);
INSERT INTO r_medical_org_main VALUES (42, 15, 981, 'ФКУ ИК-50 ГУФСИН России по Кемеровской области', 'г.Юрга, ул. Шоссейная, д.2', false);
INSERT INTO r_medical_org_main VALUES (42, 15, 990, 'ГУ ЮДИ', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 16, 1, 'МБУЗ "Беловская центральная районная больница"', 'г.Белово, п.г.т.Инской, ул.Энергетическая, д.21', true);
INSERT INTO r_medical_org_main VALUES (42, 16, 39, 'Горкинская больница', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 16, 44, 'Бачатский психоневр. интернат', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 16, 990, 'ГУ БПИ', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 17, 2, 'МБУЗ "Ижморская центральная районная больница"', 'Ижморский район, п.г.т. Ижморский, ул.Молодежная, д. 4', true);
INSERT INTO r_medical_org_main VALUES (42, 18, 151, 'МБУЗ "Центральная районная больница" Кемеровского муниципального района', 'г.Кемерово, проспект Шахтёров, д.113', true);
INSERT INTO r_medical_org_main VALUES (42, 18, 920, 'ССМП', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 18, 985, 'ФКУ ИК-22 ГУФСИН России по Кемеровской области', 'Кемеровский район, д.Мозжуха, ул.Трудовая, д.13', false);
INSERT INTO r_medical_org_main VALUES (42, 18, 990, 'ЖДИ', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 19, 1, 'МБУЗ "Крапивинская центральная районная больница"', 'Крапивинский район., п.г.т. Зеленогорский, ул.Центральная д.31', true);
INSERT INTO r_medical_org_main VALUES (42, 19, 5, 'ГКУЗ Губернский дом ребенка специализированный', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 20, 5, 'МБУЗ Центральная районная больница Ленинск-Кузнецкого муниципального района', 'г.Ленинск-Кузнецкий, ул.Суворова, д. 152', true);
INSERT INTO r_medical_org_main VALUES (42, 20, 990, 'Краснинский психоневрологический интернат', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 21, 1, 'МБУЗ "Центральная городская больница" Мариинского муниципального района', 'г.Мариинск, 1-й Микрорайон, д.5', true);
INSERT INTO r_medical_org_main VALUES (42, 21, 3, 'ГЛПУЗ Больница №2 ГУВД КО', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 21, 4, 'НУЗ "Узловая поликлиника на станции Мариинск открытого акционерного общества "Российские железные дороги"', 'г.Мариинск, ул.Вокзальная, д.3б', true);
INSERT INTO r_medical_org_main VALUES (42, 21, 6, 'Обл.туб.б-ца УН1612/33', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 21, 33, 'МУ "Городская поликлиника г.Мариинска"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 21, 40, 'Госпиталь ГУВД КО', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 21, 42, 'МУ "Городская стоматологическая поликлиника" города Мариинска и Мариинского района', 'г.Мариинск, ул.Ленина, д. 1', true);
INSERT INTO r_medical_org_main VALUES (42, 21, 43, 'МУ городской п/туберкулёзный диспансер', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 21, 44, 'Наркодиспансер', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 21, 46, 'Межрай.отд.Кем.обл.пат.бюро', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 21, 980, 'ФКУ ИК-1 ГУФСИН России по Кемеровской области', 'г.Мариинск, ул. Макаренко, д.5', false);
INSERT INTO r_medical_org_main VALUES (42, 21, 981, 'ФКУ ЛИУ-33 ГУФСИН России по Кемеровской области', 'г.Мариинск, ул. Дзержинского, д.9', false);
INSERT INTO r_medical_org_main VALUES (42, 21, 982, 'ФКУ ИК-35 ГУФСИН России по Кемеровской области', 'г.Мариинск, ул. Макаренко, д.7', false);
INSERT INTO r_medical_org_main VALUES (42, 21, 983, 'ФКУ Мариинская ВК ГУФСИН России по Кемеровской области', 'г.Мариинск, ул.Макаренко, д.4', false);
INSERT INTO r_medical_org_main VALUES (42, 21, 984, 'ФКУ СИЗО-3 ГУФСИН России по Кемеровской области', 'г.Мариинск, ул.Пальчикова, д.16', false);
INSERT INTO r_medical_org_main VALUES (42, 21, 990, 'ГУ БСИ', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 21, 991, 'МПИ', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 22, 18, 'МБУ Центральная районная больница Новокузнецкого района', 'г.Новокузнецк, пр.Пионерский, д.38', true);
INSERT INTO r_medical_org_main VALUES (42, 23, 1, 'МБУЗ "Прокопьевская центральная районная больница"', 'г.Прокопьевск, ул.Образцовая, д.11', true);
INSERT INTO r_medical_org_main VALUES (42, 23, 990, 'ГУ ППИ', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 24, 1, 'МБУЗ "Центральная районная больница Промышленновского района"', 'Кемеровская область, Промышленновский район, п.г.т.Промышленная, ул.Н.Островского, д. 78', true);
INSERT INTO r_medical_org_main VALUES (42, 24, 2, 'НУЗ "Отд. б-ца на ст. Кем." Стац. и пол. отд. на ст. Пром.', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 24, 38, 'НУЗ "Отд. б-ца на ст. Кем." Стац. и пол. отд. на ст. Пром.', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 24, 45, 'ООО "Санаторий Танай"', 'Промышленновский район, с.Ваганово, ул.Центральная, д.20', true);
INSERT INTO r_medical_org_main VALUES (42, 25, 1, 'МБУЗ "Центральная районная больница Тисульского района"', 'Тисульский район, п.г.т. Тисуль, ул.Октябрьская, д. 22', true);
INSERT INTO r_medical_org_main VALUES (42, 25, 2, 'Медико-санитарная часть МСЧ 2', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 26, 1, 'МБУЗ "Центральная районная больница Топкинского муниципального района"', 'г.Топки, ул.Революции, д.1', true);
INSERT INTO r_medical_org_main VALUES (42, 26, 2, 'НУЗ "Узл. б-ца ст.Топки ЗСЖД" (от "Отделен. б-цы Кем.")', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 26, 35, 'НУЗ "Узл. б-ца ст.Топки ЗСЖД" (от "Отделен. б-цы Кем.")', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 26, 36, 'ООО "Городская поликлиника"', 'г.Топки, ул.Горная, д. 3', false);
INSERT INTO r_medical_org_main VALUES (42, 27, 1, 'МБУЗ "Тяжинская центральная районная больница"', 'Тяжинский район, п.г.т. Тяжинский, ул. Октябрьская, д. 2', true);
INSERT INTO r_medical_org_main VALUES (42, 27, 2, 'Итатская РБ', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 27, 43, 'ССМП', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 27, 50, 'Межрай.отд. Кем.обл.пат.бюро', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 28, 1, 'МБУЗ "Центральная районная больница Чебулинского муниципального района"', 'пгт. Верх-Чебула, ул.Советская, 54', true);
INSERT INTO r_medical_org_main VALUES (42, 28, 980, 'ФКУ КП-2 ГУФСИН России по Кемеровской области', 'Чебулинский район, поселок 1-й, ул. Филина, д.2', false);
INSERT INTO r_medical_org_main VALUES (42, 28, 981, 'ФКУ КП-3 ГУФСИН России по Кемеровской области', 'Чебулинский район, пос. Новоивановский 1-й, ул. Трактовая, д.2', false);
INSERT INTO r_medical_org_main VALUES (42, 29, 34, 'МБУЗ "Юргинская центральная районная больница"', 'г.Юрга, пер.Шоссейный, 8', true);
INSERT INTO r_medical_org_main VALUES (42, 30, 1, 'МБУЗ "Яйская центральная районная больница"', 'Яйский Муниципальный район, п.г.т.Яя, ул.Авиационная, 32', true);
INSERT INTO r_medical_org_main VALUES (42, 30, 980, 'ФКУ ИК-37 ГУФСИН России по Кемеровской области', 'Яйский район, р.п.Яя ул.Жуковского, д.1', false);
INSERT INTO r_medical_org_main VALUES (42, 31, 1, 'МБУЗ Яшкинского муниципального района "Яшкинская центральная районная больница"', 'Яшкинский район, п.г.т. Яшкино, ул.Советская, д. 136', true);
INSERT INTO r_medical_org_main VALUES (42, 31, 47, 'Обл. Тутальский ревматологический санаторий', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 32, 1, 'МБУЗ "Центральная районная больница" Гурьевского муниципального района', 'г.Гурьевск, ул.Коммунистическая, д.21', true);
INSERT INTO r_medical_org_main VALUES (42, 32, 2, 'МУЗ Городская больница г.Гурьевска', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 32, 36, 'МАУ "Городская стоматологическая поликлиника" г.Гурьевска', 'г.Гурьевск, ул.30 лет Победы, 38', true);
INSERT INTO r_medical_org_main VALUES (42, 32, 40, 'Цех здоровья Металлургического завода', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 32, 45, 'ООО "Губернский центр охраны здоровья металлургов"', 'г.Гурьевск, ул. Ю.Гагарина, д.1', true);
INSERT INTO r_medical_org_main VALUES (42, 34, 1, 'МБУЗ "Центральная городская больница" г.Полысаево', 'г.Полысаево, ул.Космонавтов, д.86', true);
INSERT INTO r_medical_org_main VALUES (42, 34, 2, 'ООО "Здоровье"', 'г.Полысаево, ул.Космонавтов, д.92', true);
INSERT INTO r_medical_org_main VALUES (42, 35, 2, 'МБУЗ "Центральная городская больница"', 'г.Калтан, ул.Калинина, д.1', true);
INSERT INTO r_medical_org_main VALUES (42, 35, 43, 'МБУЗ "Городская больница № 2"', 'г.Калтан, пос.Малиновка, ул.60 лет Октября, 1', true);
INSERT INTO r_medical_org_main VALUES (42, 35, 44, 'МУЗ "Психиатрическая больница г.Калтан"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 35, 46, 'Южно-Кузб. подр. МСЧ центр зд. "Энергетик" КОАО', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 35, 48, 'МЛПУ "Противотуберкулёзный диспансер"', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 35, 49, 'Городская поликлиника 2 п.Тайжина', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 35, 50, 'Санаторий ЛУЧ', NULL, false);
INSERT INTO r_medical_org_main VALUES (42, 39, 3, 'МБУЗ "Краснобродская городская больница"', 'п.г.т.Краснобродский, ул.Гагарина, д. 6', true);
INSERT INTO r_medical_org_main VALUES (42, 39, 92, 'Узловая больница на ст.Артышта', NULL, false);
